
GET http://localhost:8080/sensorids

### devices
GET http://localhost:8080/devices

### putting
PUT http://localhost:8080/config

{
  "sensorMappings" : {
    "photovoltaic_powerflow_pv" : "thesensor:value",
    "photovoltaic_powerflow_load" : "sensore2",
    "photovoltaic_powerflow_grid" : "",
    "photovoltaic_powerflow_battery" : "",
    "battery_storage_command_mode" : "",
    "battery_state_of_charge" : "",
    "battery_discharge_limit_current" : "",
    "battery_charge_limit_current" : ""
  },
  "actorMappings" : {
    "pv_feed_in_limit" : "",
    "consumption_limit_14a" : "",
    "battery_charge_shift_pv_surplus" : "",
    "battery_discharge_shift" : "",
    "battery_grid_charge" : "",
    "battery_action_stop" : "",
    "hot_water" : "",
    "heating_target_temp" : "",
    "car_charge_start" : "",
    "car_charge_stop" : "",
    "consumer_on" : "",
    "consumer_off" : ""
  },
  "deviceMappings" : {
    "wechselrichter" : "",
    "batterie" : "",
    "waermepumpe" : "",
    "auto" : "",
    "wallbox" : "",
    "raumtemperatur" : "",
    "sonstiger_verbraucher" : ""
  }
}
